#!/usr/bin/fish

# Ensure we can find objects we've built by hand and not into debs
export LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu/

export WLR_DRM_NO_MODIFIERS=1

# Fixes issues on jetbrains ides
export _JAVA_AWT_WM_NONREPARENTING=1

# More functional tray on waybar
export XDG_CURRENT_DESKTOP=sway

# Force firefox into wayland and enable hw video decoding (ff 75+)
export MOZ_ENABLE_WAYLAND=1
export MOZ_WAYLAND_USE_VAAPI=1

# QT apps theme
export QT_QPA_PLATFORMTHEME=qt5ct

# Start ssh agent
killall ssh-agent
eval (ssh-agent -c)
find ~/.ssh ! -name "*.pub" ! -name "config" ! -name "known_hosts" -type f | xargs ssh-add 2>&1 > /dev/null

# Back previous
mv ~/logs/sway.log ~/logs/sway-prev.log

# Start sway with or without debug
argparse --name='ssway' "d/debug" -- $argv
echo $_flag_d
if test -n "$_flag_d"
    exec sway -d 2> ~/logs/sway.log
else
    exec sway 2> ~/logs/sway.log
end
