#!/usr/bin/fish

# Fixes issues on jetbrains ides
export _JAVA_AWT_WM_NONREPARENTING=1

# More functional tray on waybar
export XDG_CURRENT_DESKTOP=Unity

# Force firefox into wayland
export MOZ_ENABLE_WAYLAND=1

# QT apps theme
export QT_QPA_PLATFORMTHEME=qt5ct

# Start ssh agent
killall ssh-agent
eval (ssh-agent -c)
find ~/.ssh ! -name "*.pub" ! -name "config" ! -name "known_hosts" -type f | xargs ssh-add 2>&1 > /dev/null

# Back previous
mv ~/logs/wayfire.log ~/logs/wayfire-prev.log
exec wayfire 2> ~/logs/wayfire.log
